version: '2.1'

services:

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    networks:
    - rabbitmq_net
    ports:
    - 5672:5672
    - 15672:15672
    - 5432:5432
    
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: guest
      POSTGRES_PASSWORD: guest
    networks:
    - rabbitmq_net
    
  consumer:
    build: consumer
    restart: always
    networks:
    - rabbitmq_net
    command: python consumer.py
    depends_on:
      - db
      - rabbitmq
    
  producer:
    build: producer
    restart: always
    networks:
    - rabbitmq_net
    command: python producer.py
    stdin_open: true
    tty: true
    
networks:
  rabbitmq_net:
